# Generated by Django 5.1.2 on 2024-12-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_video_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality_name', models.CharField(max_length=150)),
            ],
        ),
    ]
