# Generated by Django 5.1.2 on 2024-11-12 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_specialists'),
    ]

    operations = [
        migrations.CreateModel(
            name='speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality_name', models.CharField(max_length=150)),
                ('id_specialists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speciality', to='api.specialists')),
            ],
        ),
    ]
