# Generated by Django 5.1.2 on 2024-11-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_speciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='institutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('province', models.CharField(max_length=150)),
            ],
        ),
    ]
