# Generated by Django 5.1.2 on 2024-11-12 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_institutions'),
    ]

    operations = [
        migrations.CreateModel(
            name='qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_name', models.CharField(max_length=150)),
                ('id_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='api.institutions')),
                ('id_specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='api.specialists')),
            ],
        ),
    ]
